import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'


export default function Home() {

  const anime_object=[
    {
      id:1,
      title: "mov 1",
      rating:4/10,
      genre:"comedy"
    },
    {
      id:1,
      title: "mov 1",
      rating:4/10,
      genre:"comedy"
    }
  ]


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
       <h2>anime project</h2>
      </main>
    </>
  )
}
